#!/bin/bash

## Remove image from .m4a(alac) for any location on disk or parent directory ##

# Specify the directory where your files are located
directory="$1"

# Use find to locate .opus files in subdirectories and iterate over them
find "$directory" -type f -name "*.m4a" -exec sh -c '
  for file do
    # Extract the filename and path
    filename=$(basename "$file")
    path=$(dirname "$file")

    # Change the extension to .webm
    new_filename="${filename%.m4a}.flac"

    # Rename the file
   ffmpeg -i  "$file" -vn -c:a flac "$path/$new_filename" ; rm "$file"
  done
' sh {} +
